### ISSUE TITLE
ошибка в примере из README.md

### ISSUE THREAD

**Issue by AlexandreZaytsev** [andrey-tech/bx24-wrapper-js#1]
вот тут 
let generator = bx24.fetchList('crm.product.list', params);
    for await (let products of generator) {
        for (let product as $products) {
            console.log('Product:', product);
        }
    }

as и $

**Comment by andrey-tech** [comment]
Благодарю! Исправлено в https://github.com/andrey-tech/bx24-wrapper-js/commit/c0d3711b22c4f10de2d1155b1ff855c9e29cc732 .
