### ISSUE TITLE
вопрос по прогресс бару при запросах к информационным блокам

### ISSUE THREAD

**Issue by AlexandreZaytsev** [andrey-tech/bx24-wrapper-js#3]
подскажите пожалуйста (Б24/облако)
для запросов к crm 
( let products = await bx24.callListMethod('crm.product.list', params);)
прогресс отрабатывает нормально 
(bx24.progress = percent => console.log(`progress: ${percent}%`);)

для запросов к инфоблокам
( let products = await bx24.callListMethod('catalog.product.list', params);)
прогресс бар не возвращает (или возвращает некорректный процент)
![image](https://user-images.githubusercontent.com/16114000/223749810-ffec2c7f-b389-436b-91a1-3dc4dc3d07c1.png)
это результат прогресса для 2675 записей

сами данные приходят нормально - а от прогресса только факт срабатывания в консоли фактически
![image](https://user-images.githubusercontent.com/16114000/223750657-f323e8c7-ecfc-416a-b9cc-74d221c1ca9d.png)

можно ли это как то поправить?

ps
с инфоблоками ('catalog.product...) вообще какая-то засада особенно для методов генераторов (fetch ) и в js и в php обертке (больше 50 не итерируются). Использовать crm для товаров не могу поскольку каталог смешанный и простые товары и торговые предложения и техподдержка б24 настоятельно рекомендует использовать методы catalog...

**Comment by andrey-tech** [comment]
Добрый день, Александр!

Напишите подробнее - при вызове метода `bx24.callListMethod('catalog.product.list', params)` для 2675 товаров в торговом каталоге: 
1) Сколько запросов в цикле реально отправляется в `Bitrix24` при вызове этого метода?
2) Сколько товаров загружается в каждом запросе к `Bitrix24`?
3) Все 2675 товаров в результате вызова метода выгружаются корректно?
4) Какова структура данных, возвращаемых в каждом запросе?

Предполагаю, как один из возможных вариантов, что для запросов `catalog.product` может возвращаться какая-то нестандартная структура данных, поэтому и прогресс бар рассчитывается некорректно. Попробуйте дебаггером посмотреть что не так происходит внутри метода `bx24.callListMethod()`.

**Comment by AlexandreZaytsev** [comment]
1. 54 (2675 товаров) запроса все по =200 ok - здесь все чисто (2675/50=53,5)
![image](https://user-images.githubusercontent.com/16114000/224029254-cfde54ce-628f-44db-a3cf-d6aebedda7eb.png)
2.  по 50 в каждом пакете кроме последнего - ответ корректный
![image](https://user-images.githubusercontent.com/16114000/224029957-7919fadc-cabb-4b23-9e21-d05025677396.png)
3.  структура товара нормальная (в отличии от crm здесь имена всех полей все в нижнем регистре) и в запросе нужно указывать обязательные параметры
			case "catalog.product.list":
			case "catalog.product.sku.list":
			case "catalog.product.offer.list":
			case "catalog.product.service.list":
    			params = {
				filter: { iblockId: catalog.value }, 
			    	select: ['*', 'id', 'iblockId' ]
//			    	select: [ 'id', 'iblockId', 'name', 'quantity', 'xmlId' ]			    	
				};				
				break;
 
![image](https://user-images.githubusercontent.com/16114000/224030999-85b81016-e3aa-447c-9a4d-6e59888cb59a.png)
![image](https://user-images.githubusercontent.com/16114000/224031168-3376fcdf-faf3-4606-a978-b278855f845d.png)

ps
метод bx24.callListMethod() посмотрю чуть позже - напишу...

**Comment by AlexandreZaytsev** [comment]
вот картинка двух методов для каталога - через CRM и через catalog - возвращают разную по вложенности структуру данных - может в этом дело. Catalog передает данные на уровень глубже...
![image](https://user-images.githubusercontent.com/16114000/224064397-b105d5a2-c237-43b1-b9d2-91c06a7bc2f8.png)
![image](https://user-images.githubusercontent.com/16114000/224065206-e5381364-08e3-4296-aca1-1b4129be1116.png)

отсюда и проблема итерации наверно,... поcкольку (не совсем владею js - чисто визуально)
crm result отдает - массив свойств 
а catalog result - объект который в свою очередь содержит массив свойств

Андрей - можно ли в вашей обертке js (да и php) учесть данное обстоятельство для запросов к информационным блокам Б24 - или дать пример функции bx24.callListMethod() для обработки данной структуры (я сам потестирую... хотя не очень в этом разбираюсь - чистый юзер)))  )

**Comment by andrey-tech** [comment]
1) Да, проблема видимо вот тут https://github.com/andrey-tech/bx24-wrapper-js/blob/master/src/bx24-wrapper.js#L134:
```js
data = data.concat(result.data());
```
В ответе ожидается массив, а фактически возвращается объект.

2) Попробуйте использовать метод `fetchList()`, в котором нет операций с массивами. Там вы сами можете решать как объединять получаемые данные.

3) Подумаю как исправить проблему с методом `callListMethod()`.

**Comment by andrey-tech** [comment]
В рамках ветки [issue-3](https://github.com/andrey-tech/bx24-wrapper-js/tree/issue-3) добавил параметр `dataExtractor`  в методы `callListMethod()` и `callLongBatch()` для корректного извлечения массива данных из результатов запроса. Попробуйте:
```js
let dataExtractor = data => data.products;

let products = await bx24.callListMethod('catalog.product.list', params, dataExtractor);

```
Если всё будет Ok, то добавлю это в релиз `v1.5.0`.

**Comment by AlexandreZaytsev** [comment]
Спасибо большое - **js прогресс бар запустился на новой сборке**
но ))
немного назад во времени (_как я понял в общении с техподдержкой Б24_)
- Битрикс24 вышел из CMS Битрикс (где все на инфоблоках) в 2012 году 
- Б24 сделал модуль CRM со своим crm каталогом на основе двух таблиц (catalog.product и catalog.price) ...да быстрее - но зачем????.... исходник под ним все равно 'базовый' и никуда не делся... - но это их дело...
- теперь (недавно) Б24 решил развить каталог на инфоблоках у себя и выделил отдельные запросы (с ускоренной фильтрацией) для товаров (старое) торговых предложений(новое) головных товаров(новое) и услуг(новое)

в итоге полная каша, вся инфа упакована в разные именные объекты... для каталога на инфоблоках имеем...
```
https://cad.bitrix24.ru/rest/catalog.product.list.json   - продукты/каталог товаров
result:{,…}
products:[{active: "Y", available: "Y", barcodeMulti: "N", bundle: "N", canBuyZero: "Y", code: null,…},…]

https://cad.bitrix24.ru/rest/catalog.product.sku.list.json  - головные товары/каталог товаров
result:{,…}
units:[{active: "Y", available: "Y", barcodeMulti: "N", bundle: "N", canBuyZero: "Y", code: "normacs",…},…]

https://cad.bitrix24.ru/rest/catalog.product.offer.list.json   - торговые предложения/каталог торговых предложений
result:{,…}
offers:[{active: "Y", available: "Y", barcodeMulti: "N", bundle: "N", canBuyZero: "Y", code: null,…},…]

https://cad.bitrix24.ru/rest/catalog.product.service.list.json - услуги/каталог товаров
result:{services: []}
services:[]
```
т.е.
```
	let dataExtractor=null;
            switch (method){
			case "catalog.price.list":
				dataExtractor = data => data.prices;
				break;   					
			case "catalog.product.list":
				dataExtractor = data => data.products;   					
				break;   					
			case "catalog.product.sku.list":
				dataExtractor = data => data.units;   					
				break;   					
			case "catalog.product.offer.list":
				dataExtractor = data => data.offers;   					
				break;   					
			case "catalog.product.service.list":
				dataExtractor = data => data.services;   					
				break;   					
//			...
		}	
	result = await bx24.callListMethod(method, params, dataExtractor)
				.catch(error => {										//ошибка конкретного промиса
					errGet(error, 'danger');
					});
```
наверно и в остальном что не входит в crm - также... не знаю... как это красиво в Вашей обертке отобразить....
(можно было бы хвост запроса отрезать, но и тут например - для головных товаров в запросе sku а в результатах units...)

по поводу feth запроса - для каталога товаров **catalog** - ругался на ID заменил на id, 
```
{
    "filter": {
        "iblockId": "21",
        ">id": 0
    },
    "select": [
        "*",
        "id",
        "iblockId"
    ],
    "order": {
        "id": "ASC"
    },
    "start": -1
}
```
говорит не может прочитать свойство id...  - наверно там тоже нужно поправить извлечение данных?
![image](https://user-images.githubusercontent.com/16114000/224303526-2761be9b-fbe1-4bd1-9841-78b892c42048.png)

а так конечно - СПАСИБО БОЛЬШОЕ - отличная библиотека и js и PHP - работаю только на ней!

**Comment by andrey-tech** [comment]
В рамках ветки [issue-3](https://github.com/andrey-tech/bx24-wrapper-js/tree/issue-3) добавил параметр `dataExtractor` в методы `fetchList()` и другие методы. Попробуйте `fetchList()` и, по возможности, также обновленные методы `callLongBatch()` и `callLargeBatch()`. Если всё будет Ok, то добавлю эти изменения также в релиз `v1.5.0`.

**Comment by AlexandreZaytsev** [comment]
нет чего-то не то
```
async function getInfo(method, params, type='list'){
	let result={};
	let bx24 = new BX24Wrapper();
//	bx24.throttle = 0.5;	//Устанавливаем троттлинг запросов к API Битрикс24 на уровне 0,5 запросов в секунду

	bx24.progress = percent => showProgressBar(percent);//console.log(`progress: ${percent}%`);//showProgressBar(percent);				//progress bar
	try {
		
			let dataExtractor=null;
            switch (method){
				case "catalog.price.list":
					dataExtractor = data => data.prices;
					break;   					
   				case "catalog.product.list":
					dataExtractor = data => data.products;   					
					break;   					
				case "catalog.product.sku.list":
					dataExtractor = data => data.units;   					
					break;   					
				case "catalog.product.offer.list":
					dataExtractor = data => data.offers;   					
					break;   					
				case "catalog.product.service.list":
					dataExtractor = data => data.services;   					
					break;   					
//				...
	
			}	
				
		if (type == "list"){									//запросить данные на промисах в массив за один раз
			result = await bx24.callListMethod(method, params, dataExtractor)
				.catch(error => {										//ошибка конкретного промиса
					errGet(error, 'danger');
					});
/*
			for (let product of result) {
				console.log('Product:', product);
			}			
*/
		} else {														//запросить данные на генераторе
			let generator = bx24.fetchList(method, params, dataExtractor);
			for await (let products of generator) {
				Array.prototype.push.apply(result,products); 				//упакуем в массив
	    	}			
		}
	}catch(err) {  // перехватит любую ошибку в блоке try: и в fetch, и в response.json
    	errGet(err, 'danger');
  	}
  	
  	bx24 = null;
// OR
//   delete bx24;	
  	
	return result;		
  }
```
искать id в order и потом его второй раз ставить там же в params.order[ idKey ] = 'ASC'; не очень хорошая идея (или я просто код не понял)
можно искать id в запросах через модуль catalog... - он 'всегда' (наверно) присутствует в массиве params.select
но... тоже как то...
может вынести наружу в плане просить формировать параметры вне запроса а не пытаться распарсить их внутри
...
хотя с dataExtractor вроде нормально смотрится...
не знаю
...
кстати ошибка там 
params.filter[ '>' . idKey ] так не сработало - может так params.filter[ '>' + idKey ] 
...
в общем в таком виде запросы полетели (в плане больше одной пачки) иногда по два за раз но все возвращают только первые 50 значений
...
пробовал вот на этом
```
   async *fetchList(method, params = {}, dataExtractor = null) {
        params.order = params.order || {};
        params.filter = params.filter || {};
        params.start = -1;

        let idKey = 'id';// in params.select ? 'id' : 'ID'; //in params.order ? 'id' : 'ID';

        params.order[ idKey ] = 'ASC';
        params.filter[ '>' + idKey ] = 0;

        let counter = 0,
            total = 0;

        this.progress(0);

        do {
            let data = await this.callMethod(method, params, dataExtractor),
                result = this.lastResult;

            if (params.filter[ '>' + idKey ] === 0) {
                total = result.total();
            }

            counter += data.length;
            this.progress(total > 0 ? Math.round(100 * counter / total) : 100);

            if (data.length === 0) {
                break;
            }
 
            yield data;

            if (! result.more()) {
                break;
            }
 
            params.filter[ '>' . idKey ] = data[ data.length - 1 ][ idKey ];

        } while (true);
    }
```
просто напрямую воткнул - пока не ясно где этот id парсить внутри или снаружи брать
параметры были такие 
![image](https://user-images.githubusercontent.com/16114000/224746464-50937909-1209-4881-bb7e-e2317004cfa3.png)

**Comment by AlexandreZaytsev** [comment]
а.. вот предлагаю так
сначала просто ищем id в params.order если его там нет пустой объект (я например не передаю id в сортировке)
то добавляем >ID:0, если есть dataExtractor!=null то меняем на >id:0 
както в эту сторону...
ps
Андрей - я не силен в конкретном синтаксисе js (пишу сразу на нескольких языках в основном desktop, в js урывками...) 

pps
данные пошли кстати, вот здесь в конце
params.filter[ '>' . idKey ] = data[ data.length - 1 ][ idKey ];
забыл поменять на
params.filter[ '>' + idKey ] = data[ data.length - 1 ][ idKey ];

**Comment by andrey-tech** [comment]
Александр, поправил метод `fetchList()`. Имя поля `ID` сущности теперь передается в метод четвертым необязательным параметром. Попробуйте.

Метод `fetchList()` реализует алгоритм [быстрого поиска от Битрикс24](https://dev.1c-bitrix.ru/rest_help/rest_sum/start.php), поэтому сортировку `ASC` по `ID` и фильтрацию `>ID`, необходимые для реализации алгоритма, приходится принудительно задавать внутри данного метода.

**Comment by AlexandreZaytsev** [comment]
да - все ок, 
а почему по пути idKey = dataExtractor!=null ? 'id' : 'ID';
```
     async *fetchList(method, params = {}, dataExtractor = null){//, idKey = 'ID') {
        params.order = params.order || {};
        params.filter = params.filter || {};
        params.start = -1;

	let idKey = dataExtractor!=null ? 'id' : 'ID';
		
        let moreIdKey = '>' + idKey,
            counter = 0,
            total = 0;
```
не пошли? все таки короче и логичней (регистр id связан с dataExtractor = с методами инфоблоков....) и нет лишнего параметра и вопросов у юзеров зачем он нужен? 
ps
проверил - работает

**Comment by AlexandreZaytsev** [comment]
на счет bath - не знаю не проверял - но разве там можно методы list использовать? - они же пойдут параллельно и мы на блокировку б24 налетаем? или нет?

**Comment by andrey-tech** [comment]
Учитывая как быстро всё меняется в Битрикс24 и полную кашу в возвращаемых объектах, не сегодня, так завтра может потребоваться, например, `dataExtractor` и для сущностей с `ID`. Предложенный вариант, на мой взгляд, даёт большую гибкость.

Про `callLongBatch()` и `callLargeBatch()` речь шла применительно не к списочным методам, а иным, например,  `crm.deal.get`, `crm.contact.get`,... В любом случае никакого параллельного исполнения тут быть не может, а будет лишь асинхронное исполнение с троттлингом запросов, заданным параметром `throttle`.

**Comment by AlexandreZaytsev** [comment]
ок, спасибо, 'длинные' батчи проверю позже - этот тикет наверно можно закрыть!

ps
ну и не могу не удержаться спросить - в php обертке аналогичные правки будут? (вложенные объекты и регистр 'id')?

**Comment by andrey-tech** [comment]
Да, планирую вскоре сделать там аналогичные доработки. Для этого создайте в том репозитории новый issue с описанием проблемы и ссылкой на данный issue.

**Comment by AlexandreZaytsev** [comment]
Ваши библиотеки тестирую здесь [https://github.com/AlexandreZaytsev/bitrix24_app_webhook_catalog_currency_etc](https://github.com/AlexandreZaytsev/bitrix24_app_webhook_catalog_currency_etc)

**Comment by andrey-tech** [comment]
Все сделанные изменения включены в релиз [v1.5.0](https://github.com/andrey-tech/bx24-wrapper-js/releases/tag/1.5.0).

Спасибо @AlexandreZaytsev
