### ISSUE TITLE
bx24.callMethod("crm.item.list", options) не возвращает total

### ISSUE THREAD

**Issue by badigit** [andrey-tech/bx24-wrapper-js#5]
Списочные методы стандартно отдают total, но в обертке он теряется.

bx24.callMethod("crm.item.list",params) //не отдает total

Специальный списочный метод - callListMethod  не особо подходит, потому что выкачивает всё.

А хотелось бы просто получить первую пачку обьектов, посмотреть total, подумать стоит ли грузить остальное. 

Либо подскажите, как через callListMethod   можно ограничить количество результатов - одной пачкой (50) + получить тотал.

**Comment by andrey-tech** [comment]
Добрый день!

Сразу после вызова `callMethod()` воспользуйтесь методом `getLastResult()` (см. документацию), который возвращает полный ответ Битрикс 24.
